In [2]:
import numpy as np
arr = np.array([10,20,30,40,50])
mean_val = np.mean(arr)
std_dev = np.std(arr)
max_val = np.max(arr)
min_val = np.min(arr)
print("Array:",arr)
print("Mean:",mean_val)
print(f"Standard Deviation: {std_dev:.2f}")
print("Maximum Value:",max_val)
print("Minimum Value:",min_val)

Array: [10 20 30 40 50]
Mean: 30.0
Standard Deviation: 14.14
Maximum Value: 50
Minimum Value: 10


In [8]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.dot(A,B)
print("Matrix A:\n",A)
print("Matrix B:\n",B)
print("Matrix Multiplication (A x B):\n",C)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Multiplication (A x B):
 [[19 22]
 [43 50]]


In [10]:
array1=np.array([1,2,3,4,5,6,7,8])
array1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
print(A.ndim)

2


In [13]:
array6=np.array([1,2,3,4,5],ndmin=2)
array6

array([[1, 2, 3, 4, 5]])

In [14]:
print(array6.ndim)

2


In [17]:
array1.shape

(8,)

In [15]:
array6.shape


(1, 5)

In [18]:
print(A[0][1])

2


In [19]:
array7=np.array([[1,2],[3.3,4]])
array7

array([[1. , 2. ],
       [3.3, 4. ]])

In [20]:
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [22]:
ch_arr2=np.array(["Supervised","unSupervised","sEMi-supervised","REINforcement"])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcement'],
      dtype='<U15')