In [1]:
import numpy as np


In [3]:
np.__version__

'1.26.4'

In [4]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [6]:
array2=np.array([[1,2],
               [3,4]])
array2

array([[1, 2],
       [3, 4]])

In [7]:
array3d=np.array([[
                   [1,2],
                   [3,4]
                 ],[
                   [5,6],
                   [7,8]
                ]] )
array3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
array3d.shape

(2, 2, 2)

In [13]:
array3ex=np.array([[
                  [1,2,3],
                  [4,5,6,],
                  [7,8,9]],
                 [[10,11,12],
                  [13,14,15],
                  [16,17,18]]
             ]                              
)
array3ex

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
array3ex.shape

(2, 3, 3)

In [16]:
array4d=np.array(
                  [[
                      [
                        [1,2],
                        [3,4],
                        [5,6]
                          
                      ],[
                          [7,8],
                          [9,10],
                          [11,12]
                      ],[
                          [13,14],
                          [15,16],
                          [17,18]
                      ]
                  ],[
                      [
                          [19,20],
                          [21,22],
                          [23,24]
                      ],[
                          [25,26],
                          [27,28],
                          [29,30]
                      ],[
                          [31,32],
                          [33,34],
                          [35,36]
                      ]
                  ]
            ]
)
array4d
    

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]]],


       [[[19, 20],
         [21, 22],
         [23, 24]],

        [[25, 26],
         [27, 28],
         [29, 30]],

        [[31, 32],
         [33, 34],
         [35, 36]]]])

In [17]:
array4d.shape

(2, 3, 3, 2)